version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    env_file:
      - ./env/backend.env
    command:
      ["rails", "server", "-b", "0.0.0.0"]
  frontend:
    build: ./frontend
    ports:
      - '3001:3001'
    env_file:
      - ./env/frontend.env
    depends_on:
      - backend